# Generated by Django 3.1.2 on 2020-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
