# Generated by Django 3.1.3 on 2020-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_example', '0003_auto_20201125_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Time',
            field=models.CharField(max_length=30),
        ),
    ]
